project_id = "gqtggvmfrgaxmobrskxr"

[functions.generate-video]
verify_jwt = true

[functions.check-video-status]
verify_jwt = true

[functions.enhance-prompt]
verify_jwt = true

[functions.generate-batch-videos]
verify_jwt = true

[functions.create-checkout]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.merge-audio-video]
verify_jwt = true
